src/Bugfree.NemLogIn.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Bugfree.NemLogIn.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Bugfree.NemLogIn.Web/Controllers/RequiresAuthenticationController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using dk.nita.saml20.identity;
using dk.nita.saml20.Schema.Core;
using dk.nita.saml20.Logging;
using dk.nita.saml20.protocol;

namespace Bugfree.NemLogIn.Web.Controllers
{
    public class AssertionModel
    {
        public List<KeyValuePair<string, string>> Assertions { get; private set; }

        public AssertionModel()
        {
            Assertions = new List<KeyValuePair<string, string>>();
        }
    }

    public class RequiresAuthenticationController : Controller
    {
        public ActionResult Index()
        {
            if (Saml20Identity.IsInitialized())
            {
                var model = new AssertionModel();
                foreach (SamlAttribute attribute in Saml20Identity.Current)
                {
                    var key = attribute.Name;
                    var value = attribute.AttributeValue.Length > 0 ? attribute.AttributeValue[0] : "";
                    model.Assertions.Add(new KeyValuePair<string, string>(key, value));
                }

                return View(model);
            }

            return Content("Saml20Indentity not initialized");
        }

        public void Logoff()
        {
            AuditLogging.logEntry(Direction.OUT, Operation.LOGOUTREQUEST, "ServiceProvider logoff requested, local user id: " + System.Web.HttpContext.Current.User.Identity.Name);
            Response.Redirect("/logout.ashx");
        }

        public void Relogin()
        {
            Response.Redirect("/login.ashx?" + Saml20AbstractEndpointHandler.IDPForceAuthn + "=true&ReturnUrl=https://oiosaml-net.dk:20002/RequiresAuthentication");
        }

        public void ReloginPassive()
        {
            Response.Redirect("/login.ashx?" + Saml20AbstractEndpointHandler.IDPIsPassive + "=true&ReturnUrl=https://oiosaml-net.dk:20002/RequiresAuthentication");
        }

        public void ReloginNoForceAuthn()
        {
            Response.Redirect("/login.ashx?ReturnUrl=https://oiosaml-net.dk:20002/RequiresAuthentication");
        }
    }
}

src/Bugfree.NemLogIn.Web/Views/Home/Index.cshtml
<h2>Home -> Index</h2>

<a href="~/RequiresAuthentication">Goto page requirering authentication</a><br />
<a href="~/Metadata.ashx">Download service metadata</a>

src/Bugfree.NemLogIn.Web/Views/RequiresAuthentication/Index.cshtml
@model Bugfree.NemLogIn.Web.Controllers.AssertionModel
<h2>Requires Authentication -> Index</h2>

<table>
    <tr>
        <th>Key</th>
        <th>Value</th>
    </tr>
    @foreach (var assertion in Model.Assertions)
    {
        <tr>
            <td>@assertion.Key</td>
            <td>@assertion.Value</td>
        </tr>
    }
</table>

<br />
<div>

    @using(Html.BeginForm("Logoff", "RequiresAuthentication"))
    {
        <input type="submit" value="Logoff" />
    }

    @using (Html.BeginForm("Relogin", "RequiresAuthentication"))
    {
        <input type="submit" value="Relogin" />
    }

    @using (Html.BeginForm("ReloginPassive", "RequiresAuthentication"))
    {
        <input type="submit" value="ReloginPassive" />
    }

    @using (Html.BeginForm("ReloginNoForceAuthn", "RequiresAuthentication"))
    {
        <input type="submit" value="ReloginNoForceAuthn" />
    }

</div>

src/Bugfree.NemLogIn.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bugfree.NemLogIn", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>